# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             4.0.0
github:
  repo:              https://github.com/josephfusco/dogedir

# Gems
gems:
  - jekyll-paginate
  - jekyll-redirect-from
